FROM scireum/s3-ninja:6.5.2





# Inclua todos os buckets que precisa no comando a seguir

RUN mkdir -p /home/sirius/data/bucket_teste && \
    mkdir -p /home/sirius/data/bucket_privado && \
    mkdir -p /home/sirius/data/bucket_privado_mural && \
    mkdir -p /home/sirius/data/bucket_publico_mural 

USER sirius